# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github

repository:
  name: user-odm-pack
  description: 👤 A pack for NucleosUserBundle with MongoDB support
  homepage: https://docs.nucleos.rocks
  topics: hacktoberfest, symfony, symfony-pack

branches:
  - name: main
    protection:
      enforce_admins: false
      required_status_checks:
        contexts:
          - "Coding Standards (8.0)"
        strict: true

      required_pull_request_reviews: null
      restrictions: null
